src/data/entities.yml, src/data/projects.yml
Add missing entries or links in in "other tools" and "resource" sections by:
- either add data and regenerate the `projects.yml` file
- or add entries in `entities.yml` file
https://stateofjs2019.netlify.com/javascript-flavors/other-tools/
- Kotlin `https://kotlinlang.org`
- Scala `https://scala-lang.org`
- vanillajs: alias added
- Dart `https://dart.dev`
https://stateofjs2019.netlify.com/front-end-frameworks/other-tools/
Aliases added:
- cycle
- angularjs
- reactnative
https://stateofjs2019.netlify.com/other-tools/
- Moment link fixed
https://stateofjs2019.netlify.com/resources/
Added entries:
- david_walsh
- dailyjs
- echojs
- kentcdodds
- overreacted
- 2ality
- scotchio
- node_weekly
- hackernoon
- react_status
- robin_wieruch
- ember_times …
=> Add missing data in "other tools" and "resource" sections

src/data/entities.yml
=> Add JavaScript.info to resources list

src/i18n-old/locales.yml, src/i18n/locales.yml
Hey @SachaG 
Can you please merge this PR.
It includes the locale contributor list updates.
=> feat(locales):Added contributor.

src/i18n/ru-RU/common.yml
According to https://github.com/StateOfJS/state-of-js-graphql-results-api/commit/c18a89afadc664cc43326f14fad50970bb2fa791
=> Add new Russian translation

src/i18n/en-US/common.yml, src/i18n/fr-FR/common.yml, src/i18n/it-IT/common.yml, src/i18n/model/common.yml, src/i18n/pl-PL/common.yml, src/i18n/pt-PT/common.yml, src/i18n/ru-RU/common.yml, src/i18n/sv-SE/common.yml, src/i18n/zh-Hans/common.yml
=> Display proper choice text  in years of experience answer

src/i18n/cs-CZ/common.yml, src/i18n/cs-CZ/homepage.yml, src/i18n/model/common.yml
@SachaG It looks like the model YAML was out of sync with actual keys used so I tried to fix it.
=> Fix translation keys in model YAML and CZ localisation 🇨🇿

src/i18n/locales.yml, src/i18n/zh-Hant/common.yml, src/i18n/zh-Hant/homepage.yml, src/i18n/zh-Hant/state_of_css.yml
=> Supplementary Mandarin updates

src/i18n-old/common/es-ES.yml, src/i18n-old/common/model.yml, src/i18n/hi-IN/common.yml, src/i18n/pl-PL/common.yml, src/i18n/tr-TR/common.yml
There is a mix between the old race selector (the experiment with the emojis) and the new classic race selector. So I replaced the old ones.
=> Remove old skin tone appearance structure.

src/i18n-old/homepage/en-US.yml, src/i18n-old/homepage/model.yml, src/i18n-old/state_of_css/en-US.yml, src/i18n-old/state_of_css/model.yml, src/i18n-old/state_of_css/zh-Hans.yml, src/i18n/en-US/homepage.yml, src/i18n/hi-IN/homepage.yml, src/i18n/pl-PL/homepage.yml, src/i18n/sv-SE/homepage.yml, src/i18n/zh-Hans/homepage.yml
I think it wrong to use `latests trends` because adjectives have no plural in English.
=> Fix typo in plural adjective.

src/i18n-old/common/model.yml, src/i18n-old/homepage/it-IT.yml, src/i18n/hi-IN/common.yml, src/i18n/it-IT/homepage.yml, src/i18n/model/accounts.yml, src/i18n/model/common.yml, src/i18n/model/homepage.yml, src/i18n/model/state_of_css.yml, src/i18n/pl-PL/common.yml, src/i18n/tr-TR/common.yml
* There are a few extra `#` that I have removed.
* There are some `en-US` instead of an `ADD LOCALE HERE` in the model files.
* There is a mismatch between the English translation `CSS pseudo-elements` and the model `CSS selectors`. So I left in the model the English translation.
=> Remove extra characters and fix typos.

src/i18n-old/common/es-ES.yml, src/i18n-old/state_of_css/es-ES.yml, src/i18n-old/state_of_js/es-ES.yml, src/i18n/es-ES/accounts.yml, src/i18n/es-ES/common.yml, src/i18n/es-ES/homepage.yml, src/i18n/es-ES/results.yml, src/i18n/es-ES/state_of_css.yml, src/i18n/es-ES/state_of_js.yml, src/i18n/hi-IN/state_of_css.yml
* I have improved some Spanish expressions in the translations.
* I have added missing translations.
* I have reverted some structural changes done by my IDE (sorry).
* I have fixed a typo in `options.combinators.next_subling`.
* I have fixed this key `opinions.currently_missing_from_css.others` using this other key `opinions_other.currently_missing_from_css.others.description` because there were missing translations.
=> Fix Spanish language and some bugs.

src/i18n-old/common/model.yml, src/i18n/pl-PL/common.yml, src/i18n/tr-TR/common.yml
There are mixed keys in `common > options` from the old format.
=> Fix keys in common options.

src/i18n/zh-Hant/common.yml, src/i18n/zh-Hant/state_of_css.yml
=> Another zh-Hant 🇹🇼🇭🇰 supplementary update

src/i18n/zh-Hant/common.yml, src/i18n/zh-Hant/state_of_css.yml, src/i18n/zh-Hant/state_of_js.yml
=> Update zh-Hant🇹🇼🇭🇰 strings for css surveys

src/i18n/es-ES/state_of_css.yml
Backporting changes from https://github.com/StateOfJS/Translations/pull/2
cc @SachaG
=> Fix typos in Spanish translation

src/i18n/tr-TR/common.yml, src/i18n/tr-TR/results.yml, src/i18n/tr-TR/state_of_css.yml, src/i18n/tr-TR/state_of_css_2020.yml, src/i18n/tr-TR/state_of_js.yml
Non formal usage corrected, newly added TODOs translated and this years CSS result that added at [41de34f](https://github.com/StateOfJS/state-of-js-graphql-results-api/commit/41de34f13a316818edd12ea9b0bafd2bb9981df3) and [1a1038d](https://github.com/StateOfJS/state-of-js-graphql-results-api/commit/1a1038dbcebaa5bb38bd91ef1124fc83439aaa01) which mentioned in [this comment](https://github.com/StateOfJS/state-of-js-graphql-results-api/issues/50#issuecomment-729387462) at #50 translated.
=> State of css 2020 results tr-TR translation and some corrections

src/i18n/cs-CZ/common.yml, src/i18n/de-DE/common.yml, src/i18n/de-DE/results.yml, src/i18n/en-US/common.yml, src/i18n/en-US/results.yml, src/i18n/es-ES/common.yml, src/i18n/es-ES/results.yml, src/i18n/fr-FR/common.yml, src/i18n/hi-IN/common.yml, src/i18n/id-ID/common.yml, src/i18n/it-IT/common.yml, src/i18n/pl-PL/common.yml, src/i18n/pt-PT/common.yml, src/i18n/ru-RU/common.yml, src/i18n/ru-RU/results.yml, src/i18n/sv-SE/common.yml, src/i18n/tr-TR/common.yml, src/i18n/tr-TR/results.yml, src/i18n/zh-Hans/common.yml, src/i18n/zh-Hant/common.yml
Not all footer links work now.
cc @SachaG
=> Fix links interpolations

src/i18n/de-DE/results.yml, src/i18n/en-US/results.yml, src/i18n/en-US/state_of_css_2020.yml, src/i18n/es-ES/results.yml, src/i18n/ru-RU/results.yml
=> Added missing dots

src/data/entities/libraries.yml, src/data/entities/sites.yml
=> Fix some nits

src/i18n/ru-RU/state_of_js.yml
=> Fix typos in Russian translation

src/i18n/fr-FR/common.yml
*Compétences* instead of *Cométences*
=> Fix small typo

src/i18n/pl-PL/accounts.yml, src/i18n/pl-PL/common.yml, src/i18n/pl-PL/homepage.yml, src/i18n/pl-PL/results.yml, src/i18n/pl-PL/state_of_css.yml, src/i18n/pl-PL/state_of_css_2020.yml, src/i18n/pl-PL/state_of_js.yml, src/i18n/pl-PL/state_of_js_2020.yml, src/i18n/pl-PL/state_of_js_2020_survey.yml, src/i18n/pl-PL/surveys.yml
Feel free to suggest improvements, find typos etc if you're a polish speaker ❤️
=> Add Polish translation 🇵🇱

src/i18n/ja-JP/state_of_js.yml
part of the Japanese translation effort (see #107 for progress).
=> translate state_of_js.yml into Japanese

src/i18n/locales.yml, src/i18n/pl-PL/homepage.yml, src/i18n/pl-PL/state_of_css_2020.yml
=> Update PL translation & locales.yml

src/i18n/locales.yml, src/i18n/zh-Hant/results.yml
- Update the `zh-Hant` translator list
- Update `zh-Hant` translation of `results.yml`
=> Translate the newly added content of results.yml into Traditional Chinese

src/i18n/locales.yml, src/i18n/pl-PL/homepage.yml, src/i18n/pl-PL/state_of_css_2020.yml
=> Update pl translation

src/i18n/zh-Hant/results.yml
Adjust some of the translations according to https://github.com/StateOfJS/state-of-js-graphql-results-api/pull/119
=> Improve Traditional Chinese translation of results.yml

.github/CODEOWNERS, src/i18n/de-DE/results.yml, src/i18n/en-US/results.yml, src/i18n/es-ES/results.yml, src/i18n/fa-IR/results.yml, src/i18n/ja-JP/results.yml, src/i18n/pl-PL/results.yml, src/i18n/ru-RU/results.yml, src/i18n/tr-TR/results.yml, src/i18n/ua-UA/results.yml, src/i18n/zh-Hant/results.yml
=> Add missing details for PL translation

src/i18n/en-US/state_of_js_2020.yml
=> Fix various naming issues

src/i18n/ru-RU/results.yml
=> Fix satisfaction note key in Russian translation

src/i18n/es-ES/state_of_js_2020.yml, src/i18n/es-ES/state_of_js_2020_survey.yml, src/i18n/es-ES/surveys.yml
Files updated:
- /state_of_js_2020.yml
- /state_of_js_2020_survey.yml
- /surveys.yml
=> Spanish translations

src/i18n/es-ES/common.yml
Missing translations for common.yml
=> Spanish translation: common.yml

src/i18n/locales.yml, src/i18n/zh-Hans/accounts.yml, src/i18n/zh-Hans/common.yml, src/i18n/zh-Hans/state_of_css.yml, src/i18n/zh-Hans/state_of_js.yml
Hi!
I added and corrected part of the translation of zh-Hans, and removed some `#TODO` on the key which had already translated.
cc @SachaG
=> feat: added and corrected part of the translation of zh-Hans

src/i18n/en-US/results.yml, src/i18n/es-ES/accounts.yml, src/i18n/es-ES/common.yml, src/i18n/es-ES/homepage.yml, src/i18n/es-ES/results.yml, src/i18n/es-ES/state_of_css.yml, src/i18n/es-ES/state_of_css_2020.yml, src/i18n/es-ES/state_of_js.yml, src/i18n/es-ES/state_of_js_2020.yml, src/i18n/es-ES/state_of_js_2020_survey.yml
I have added missing Spanish strings comparing directly with the English version of the files. Happy New Year!
=> Add new Spanish translations.

src/i18n/gl-ES/accounts.yml, src/i18n/gl-ES/common.yml, src/i18n/gl-ES/homepage.yml, src/i18n/gl-ES/results.yml, src/i18n/gl-ES/state_of_css.yml, src/i18n/gl-ES/state_of_css_2020.yml, src/i18n/gl-ES/state_of_js.yml, src/i18n/gl-ES/state_of_js_2020.yml, src/i18n/gl-ES/state_of_js_2020_survey.yml, src/i18n/gl-ES/surveys.yml, src/i18n/index.ts, src/i18n/locales.yml
=> Translate to Galician

src/i18n/es-ES/common.yml, src/i18n/es-ES/results.yml
One question: when do **untranslatedKeys**  from the API response gets updated?
=> Missing spanish translations for: results.yml

src/data/entities/podcasts.yml, src/data/entities/sites.yml
Naming resources as they represent themselves.
сс @SachaG
=> Clarify some resource names
